
spring:
  datasource:
    url: jdbc:postgresql://gohard.iptime.org:5432/roadking_db
    username: roadking
    password: roadking123
    driver-class-name: org.postgresql.Driver

  devtools:
    livereload:
      enabled: true
  thymeleaf:
    cache: false


  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100 # in (?,?, ... )  in 쿼리로 한번에 땡겨오는 데이터 개수

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

#server 설정
server:
#  port: 8080
  port: 58824 #linux 서버컴 포트

logging:
  level:
    org.hibernate.SQL: debug
#    org.hibernate.type: trace
