name: Congressman_Analysis

on:
  push:
    branches:
      - main
  workflow_dispatch: # (2) 수동 실행

jobs:
  build:
    runs-on: ubuntu-20.04 # (3)
    env:
      APPLICATION_MAIN: ${{ secrets.APPLICATION_MAIN }}
      APPLICATION_TEST: ${{ secrets.APPLICATION_TEST }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3 # (4)

      - name: Set up JDK 11
        uses: actions/setup-java@v3 # (5)
        with:
          distribution: 'adopt'
          java-version: '11'

      - run: touch ./src/main/resources/application_main.yml
      - run: echo "$APPLICATION_MAIN" > ./src/main/resources/application_main.yml
      - run: cat ./src/main/resources/application_main.yml

      - run: touch ./src/test/resources/application_test.yml
      - run: echo "$APPLICATION_TEST" > ./src/main/resources/application_test.yml
      - run: cat ./src/main/resources/application_test.yml

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew # (6)
        shell: bash

      - name: Build with Gradle
        run: ./gradlew clean build # (7)
        shell: bash